server:
  port: 9091

spring:
  application:
    name: eureka-server9091

eureka:
  instance:
    hostname: eureka9091
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#逗号之间不能有空格
      defaultZone: http://eureka9090:9090/eureka/,http://eureka9092:9092/eureka/

