server:
  port: 9092

spring:
  application:
    name: eureka-server9092

eureka:
  instance:
    hostname: eureka9092
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka9091:9091/eureka/,http://eureka9090:9090/eureka/

