server:
  port: 8082

spring:
  application:
    name: microservice-comsumer-8082

consumer_8082:
  ip: localhost
  rest_url_prefix: http://${consumer_8082.ip}:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    instance-id: comsumer-8082
    prefer-ip-address: true
