server:
  port: 7071

spring:
  application:
    name: microservice-comsumer--feign-7071

eureka:
  client:
    service-url:
      defaultZone: http://eureka9091:9091/eureka/,http://eureka9092:9092/eureka/,http://eureka9090:9090/eureka/
  instance:
    instance-id: comsumer-7071
    prefer-ip-address: true
